services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000/api
    networks:
      - plataforma-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=plataforma-net"

  gestor-app:
    build: ./gestor_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/app/workspace
      - ./data:/app/data
    networks:
      - plataforma-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gestor.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gestor.priority=10"
      - "traefik.http.services.gestor.loadbalancer.server.port=8080"
      - "traefik.docker.network=plataforma-net"

  reverse-proxy:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - plataforma-net

networks:
  plataforma-net:
    driver: bridge